In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('E:\Deep-learning\Regresssion_problem\Admission_Prediction.csv')

In [3]:
df.head()

,Serial_No.,GRE_Score,TOEFL_Score,University_Rating,SOP,LOR,CGPA,Research,Chance_of_Admit
0,1,337.0,118.0,4,4.5,4.5,9.65,Yes,0.92
1,2,324.0,107.0,4,4.0,4.5,8.87,Yes,0.76
2,3,316.0,104.0,3,3.0,3.5,8.00,Yes,0.72
3,4,322.0,110.0,3,3.5,2.5,8.67,Yes,0.80
4,5,314.0,103.0,2,2.0,3.0,8.21,No,0.65

In [4]:
df.shape

(505, 9)

In [5]:
df.drop(columns=['Serial_No.'],inplace=True)

In [6]:
df.head()

,GRE_Score,TOEFL_Score,University_Rating,SOP,LOR,CGPA,Research,Chance_of_Admit
0,337.0,118.0,4,4.5,4.5,9.65,Yes,0.92
1,324.0,107.0,4,4.0,4.5,8.87,Yes,0.76
2,316.0,104.0,3,3.0,3.5,8.00,Yes,0.72
3,322.0,110.0,3,3.5,2.5,8.67,Yes,0.80
4,314.0,103.0,2,2.0,3.0,8.21,No,0.65

In [13]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [15]:
X_train

     GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA
442      318.0        110.0                  1  2.5  3.5  8.54
42       313.0        107.0                  2  2.5  2.0  8.50
58       300.0         99.0                  1  3.0  2.0  6.80
481      309.0        105.0                  4  3.5  2.0  8.18
78       296.0         95.0                  2  3.0  2.0  7.54
..         ...          ...                ...  ...  ...   ...
255      318.0        100.0                  2  2.5  3.5  8.54
72       321.0        111.0                  5  5.0  5.0  9.45
396      326.0        112.0                  4  4.0  3.5  9.12
235      312.0        107.0                  2  2.5  3.5  8.27
37       300.0        105.0                  1  1.0  2.0  7.80

[404 rows x 6 columns]

In [11]:
df.drop(columns=['Research'],inplace=True)
df.head()

   GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA  Chance_of_Admit
0      337.0        118.0                  4  4.5  4.5  9.65             0.92
1      324.0        107.0                  4  4.0  4.5  8.87             0.76
2      316.0        104.0                  3  3.0  3.5  8.00             0.72
3      322.0        110.0                  3  3.5  2.5  8.67             0.80
4      314.0        103.0                  2  2.0  3.0  8.21             0.65

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
X_test
X_test_scaled

array([[ 0.46      ,  0.5       ,  0.25      ,  0.375     ,  0.14285714,
         0.5224359 ],
       [ 0.44      ,  0.53571429,  0.5       ,  0.5       ,  0.42857143,
         0.53205128],
       [ 0.98      ,  0.96428571,  1.        ,  0.875     ,  0.71428571,
         0.92948718],
       [ 0.52      ,  0.53571429,  0.25      ,  0.625     ,  0.57142857,
         0.58974359],
       [ 0.48      ,  0.46428571,  0.25      ,  0.375     ,  0.14285714,
         0.26923077],
       [ 0.38      ,  0.46428571,  1.        ,  0.625     ,  0.57142857,
         0.56410256],
       [ 0.46      ,  0.60714286,  0.5       ,  0.75      ,  0.57142857,
         0.70512821],
       [ 0.74      ,  0.39285714,  0.5       ,  0.75      ,  0.71428571,
         0.48076923],
       [ 0.64      ,  0.71428571,  0.75      ,  0.875     ,  0.85714286,
         0.78846154],
       [ 0.56      ,  0.5       ,  0.25      ,  0.75      ,  0.71428571,
         0.35897436],
       [ 0.28      ,  0.42857143,  0.5       ,  0.375     ,  0.14285714,
         0.42307692],
       [ 0.72      ,  0.64285714,  0.5       ,  0.625     ,  0.57142857,
         0.62820513],
       [ 0.74      ,  0.42857143,  1.        ,  0.5       ,  0.57142857,
         0.65384615],
       [ 0.74      ,  0.78571429,  0.5       ,  0.5       ,  0.42857143,
         0.71153846],
       [ 0.36      ,  0.64285714,  0.75      ,  0.625     ,  0.42857143,
         0.57692308],
       [ 0.68      ,  0.60714286,  0.5       ,  0.625     ,  0.42857143,
         0.68589744],
       [ 0.68      ,  0.64285714,  0.5       ,  0.625     ,  0.42857143,
         0.77564103],
       [        nan,  0.60714286,  0.25      ,  0.5       ,  0.71428571,
         0.52884615],
       [        nan,  0.39285714,  0.5       ,  0.375     ,  0.42857143,
         0.55769231],
       [ 0.72      ,  0.78571429,  0.5       ,  0.5       ,  0.42857143,
         0.74038462],
       [ 0.42      ,  0.53571429,  0.75      ,  0.875     ,  0.85714286,
         0.70512821],
       [ 0.5       ,  0.46428571,  0.5       ,  0.25      ,  0.28571429,
         0.53846154],
       [ 0.76      ,  0.57142857,  0.75      ,  0.875     ,  0.71428571,
         0.76282051],
       [ 0.66      ,  0.42857143,  0.5       ,  0.75      ,  0.71428571,
         0.52564103],
       [ 0.7       ,  0.71428571,  0.75      ,  0.625     ,  0.57142857,
         0.67948718],
       [ 0.18      ,  0.28571429,  0.5       ,  0.25      ,  0.42857143,
         0.19871795],
       [ 0.82      ,  0.71428571,  1.        ,  0.75      ,  1.        ,
         0.96153846],
       [ 0.36      ,  0.5       ,  0.5       ,  0.5       ,  0.42857143,
         0.46153846],
       [ 0.72      ,  0.35714286,  0.75      ,  1.        ,  1.        ,
         0.62820513],
       [ 1.        ,  0.75      ,  0.75      ,  1.        ,  1.        ,
         0.94230769],
       [ 0.24      ,  0.25      ,  0.        ,  0.25      ,  0.14285714,
         0.14423077],
       [ 0.68      ,  0.82142857,  0.5       ,  0.625     ,  0.42857143,
         0.62820513],
       [ 0.88      ,  1.        ,  1.        ,  0.75      ,  1.        ,
         0.98397436],
       [ 0.82      ,  0.85714286,  0.75      ,  0.875     ,  0.85714286,
         0.84615385],
       [ 0.1       ,  0.32142857,  0.25      ,  0.375     ,  0.14285714,
         0.33974359],
       [ 0.64      ,  0.71428571,  0.5       ,  0.5       ,  0.71428571,
         0.58333333],
       [ 0.84      ,  0.71428571,  0.        ,  0.125     ,  0.42857143,
         0.59615385],
       [ 0.48      ,  0.39285714,  0.25      ,  0.25      ,  0.42857143,
         0.45192308],
       [ 0.76      ,  0.85714286,  1.        ,  0.875     ,  1.        ,
         0.73076923],
       [ 0.62      ,  0.35714286,  0.5       ,  0.625     ,  0.71428571,
         0.70833333],
       [ 0.18      ,  0.28571429,  0.5       ,  0.25      ,  0.14285714,
         0.39102564],
       [ 0.42      ,  0.46428571,  0.25      ,  0.5       ,  0.14285714,
         0.42307692],
       [ 0.52      ,  0.64285714,  0.5       ,  0.625     ,  0.71428571,
         0.56410256],
       [ 0.6       ,  0.64285714,  1.        ,  0.75      ,  0.71428571,
         0.79166667],
       [ 0.54      ,  0.42857143,  0.25      ,  0.5       ,  0.42857143,
         0.62820513],
       [ 0.62      ,  0.64285714,  0.75      ,  0.625     ,  0.71428571,
         0.49679487],
       [ 0.56      ,  0.60714286,  0.5       ,  0.5       ,  0.42857143,
         0.54487179],
       [ 0.56      ,  0.39285714,  0.5       ,  0.75      ,  0.85714286,
         0.54166667],
       [ 0.64      ,  0.64285714,  1.        ,  0.875     ,  0.71428571,
         0.69551282],
       [ 0.48      ,  0.5       ,  0.25      ,  0.75      ,  0.57142857,
         0.46474359],
       [ 0.66      ,  0.64285714,  0.75      ,  0.75      ,  1.        ,
         0.66666667],
       [ 0.18      ,  0.28571429,  0.        ,  0.125     ,  0.14285714,
         0.34935897],
       [ 0.8       ,  0.82142857,  1.        ,  0.875     ,  0.42857143,
         0.81410256],
       [ 0.06      ,  0.17857143,  0.25      ,  0.25      ,  0.71428571,
         0.32051282],
       [ 0.9       ,  0.89285714,  1.        ,  1.        ,  1.        ,
         0.96794872],
       [ 0.28      ,  0.46428571,  0.25      ,  0.5       ,  0.42857143,
         0.44871795],
       [ 0.8       ,  0.78571429,  0.75      ,  0.875     ,  0.42857143,
         0.75961538],
       [ 0.44      ,  0.57142857,  0.5       ,  0.625     ,  0.42857143,
         0.55448718],
       [ 0.58      ,  0.5       ,  0.5       ,  0.75      ,  0.42857143,
         0.38461538],
       [ 0.58      ,  0.5       ,  0.5       ,  0.625     ,  0.28571429,
         0.49038462],
       [ 0.74      ,  0.5       ,  0.75      ,  0.75      ,  0.85714286,
         0.625     ],
       [ 0.58      ,  0.39285714,  0.75      ,  0.875     ,  0.57142857,
         0.59615385],
       [ 0.8       ,  1.        ,  1.        ,  0.875     ,  1.        ,
         0.88461538],
       [ 0.66      ,  0.67857143,  1.        ,  0.75      ,  1.        ,
         0.98076923],
       [ 0.96      ,  1.        ,  0.75      ,  1.        ,  1.        ,
         0.91666667],
       [        nan,  0.57142857,  0.5       ,  0.375     ,  0.42857143,
         0.42307692],
       [ 0.46      ,  0.42857143,  0.5       ,  0.75      ,  0.85714286,
         0.59294872],
       [ 0.68      ,  0.53571429,  1.        ,  0.625     ,  0.71428571,
         0.59615385],
       [ 0.2       ,  0.35714286,  0.25      ,  0.125     ,  0.14285714,
         0.34294872],
       [ 0.78      ,  0.67857143,  0.75      ,  0.875     ,  0.71428571,
         0.70833333],
       [ 0.3       ,  0.35714286,  0.25      ,  0.25      ,  0.28571429,
         0.44230769],
       [ 0.58      ,  0.46428571,  0.5       ,  0.5       ,  0.57142857,
         0.59935897],
       [ 0.96      ,  0.82142857,  1.        ,  0.875     ,  1.        ,
         0.77884615],
       [ 0.4       ,  0.25      ,  0.25      ,  0.125     ,  0.14285714,
         0.16025641],
       [ 0.96      ,  0.89285714,  0.75      ,  0.625     ,  0.85714286,
         0.8525641 ],
       [ 0.28      ,  0.53571429,  0.5       ,  0.625     ,  0.42857143,
         0.33974359],
       [ 0.52      ,  0.35714286,  0.25      ,  0.75      ,  0.57142857,
         0.43269231],
       [ 0.44      ,  0.5       ,  0.5       ,  0.75      ,  0.57142857,
         0.63782051],
       [ 0.14      ,  0.28571429,  0.        ,  0.125     ,  0.14285714,
         0.3525641 ],
       [        nan,  0.42857143,  0.75      ,  1.        ,  1.        ,
         0.71153846],
       [ 0.72      ,  0.71428571,  0.5       ,  0.625     ,  0.42857143,
         0.73717949],
       [ 0.        ,  0.42857143,  0.75      ,  0.25      ,  0.28571429,
         0.21153846],
       [ 0.82      ,  0.82142857,  1.        ,  0.875     ,  0.57142857,
         0.82051282],
       [ 0.42      ,  0.42857143,  0.5       ,  0.75      ,  0.57142857,
         0.42628205],
       [ 0.18      ,  0.07142857,  0.        ,  0.        , -0.14285714,
         0.17307692],
       [ 0.54      ,  0.28571429,  0.25      ,  0.5       ,  0.28571429,
         0.56730769],
       [ 0.34      ,  0.46428571,  0.25      ,  0.375     ,  0.85714286,
         0.42307692],
       [ 0.48      ,  0.53571429,  0.25      ,  0.375     ,  0.71428571,
         0.47115385],
       [ 0.14      ,  0.25      ,  0.75      ,  0.5       ,  0.57142857,
         0.32371795],
       [ 0.48      ,  0.60714286,  0.75      ,  0.625     ,  0.71428571,
         0.63141026],
       [ 0.42      ,  0.25      ,  0.        ,  0.375     ,  0.42857143,
         0.5224359 ],
       [ 0.62      ,  0.78571429,  0.75      ,  0.75      ,  1.        ,
         0.74358974],
       [ 0.42      ,  0.32142857,  0.25      ,  0.375     ,  0.57142857,
         0.49358974],
       [ 0.62      ,  0.60714286,  0.5       ,  0.5       ,  0.71428571,
         0.44871795],
       [ 0.64      ,  0.71428571,  0.75      ,  0.625     ,  0.28571429,
         0.71153846],
       [ 0.74      ,         nan,  0.75      ,  0.75      ,  0.85714286,
         0.70512821],
       [ 0.84      ,  0.57142857,  1.        ,  0.875     ,  0.71428571,
         0.71153846],
       [ 0.16      ,  0.21428571,  0.25      ,  0.75      ,  0.42857143,
         0.39423077],
       [ 0.68      ,  0.75      ,  0.75      ,  0.875     ,  0.71428571,
         0.63782051],
       [ 0.3       ,  0.57142857,  1.        ,  0.5       ,  0.42857143,
         0.53846154],
       [ 0.62      ,  0.71428571,  0.5       ,  0.5       ,  0.85714286,
         0.68910256]])

In [27]:
import tensorflow 
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [28]:
model =Sequential()
model.add(Dense(7, activation='relu', input_dim=6))
model.add(Dense(1, activation='linear'))

AttributeError: module 'tensorflow.python.trackable.data_structures' has no attribute 'sticky_attribute_assignment'